# Config file for automatic testing at travis-ci.org

sudo: required

language: c

# My very smart trick to force inclusion of the veth kernel module
# (even though we do not use docker at all her)
services:
  - docker

env:
  - PYP_ADD="/usr/local/lib/python2.7/dist-packages:/usr/local/lib/python2.7/site-packages"

# There is probably some redundant stuff in this list. If you find one, remove
# it 
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - libjudy-dev
      - libgmp-dev
      - libpcap-dev
      - libboost1.55-dev
      - libboost-test1.55-dev
      - libboost-program-options1.55-dev
      - libboost-system1.55-dev
      - libboost-filesystem1.55-dev
      - libboost-thread1.55-dev
      - libboost-test1.55-dev
      - libevent-dev
      - automake
      - libtool
      - flex 
      - bison
      - pkg-config
      - g++-4.8
      - libssl-dev
      - doxygen
      - git
      - libedit-dev
      - libevent-dev
      - libfreetype6-dev
      - libpng-dev
      - libyaml-0-2
      - libbz2-dev
      - libnl-route-3-dev
      - openssl
      - pkg-config
      - python-dev
      - python-matplotlib
      - python-numpy
      - python-pip
      - python-scipy
      - python-setuptools
      - python-yaml

# need to replace github ssh references with https
before_install:
  - git submodule update --init --recursive
  - sudo apt-get install ethtool
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade thrift
  - sudo pip install ctypesgen
  - sudo pip install crc16
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 99

# install bmv2 before p4c-bmv2 to get nanomsg
install:
  - wget https://s3-us-west-2.amazonaws.com/p4lang/thrift_bin.tar.gz
  - tar -xzvf thrift_bin.tar.gz -C $HOME/
  - export PATH=$PATH:$HOME/thrift/bin/
  - export LDFLAGS="$LDFLAGS -L$HOME/thrift/lib"
  - export CPPFLAGS="$CPPFLAGS -I$HOME/thrift/include"
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/thrift/lib
  - mkdir install_tmp && cd install_tmp/
  - sudo apt-get remove python-scapy
  - git clone https://github.com/p4lang/scapy-vxlan.git && cd scapy-vxlan && sudo python setup.py install && cd ..
  - cd .. && sudo rm -rf install_tmp/
  - bash CI/travis/install-ptf.sh
  - bash CI/travis/install-bmv2.sh
  - bash CI/travis/install-p4c-bmv2.sh
  - export PYTHONPATH=$PYP_ADD:$PYTHONPATH
  - sudo ldconfig
  - ./autogen.sh; ./configure --with-bmv2 --with-switchsai; make -j2

before_script:
  - cp CI/travis/veth_setup.sh tools/
  - cd tools; sudo ./veth_setup.sh; sudo ./veth_disable_ipv6.sh; cd ..

# TODO: improve
script:
  - sudo ./bmv2/run_bm.sh &>/dev/null &
  - sleep 10
  - sudo ./bmv2/run_drivers.sh &>/dev/null &
  - sleep 10
  - sudo PYTHONPATH=$PYP_ADD:$PYTHONPATH ./bmv2/run_tests.sh
  - sudo killall bmswitchp4_drivers lt-bmswitchp4_drivers simple_switch lt-simple_switch; echo 0
  - sudo ./bmv2/run_bm.sh &>/dev/null &
  - sleep 10
  - sudo ./bmv2/run_drivers.sh &>/dev/null &
  - sleep 10
  - sudo PYTHONPATH=$PYP_ADD:$PYTHONPATH ./bmv2/run_tests.sh --test-dir tests/ptf-tests/api-tests/
  - sudo killall bmswitchp4_drivers lt-bmswitchp4_drivers simple_switch lt-simple_switch; echo 0
  - sudo ./bmv2/run_bm.sh &>/dev/null &
  - sleep 10
  - sudo ./bmv2/run_drivers.sh &>/dev/null &
  - sleep 10
  - sudo PYTHONPATH=$PYP_ADD:$PYTHONPATH ./bmv2/run_tests.sh --test-dir tests/ptf-tests/sai-tests
